version: "3"
services:
  nginx: 
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
      - api
    volumes:
      - ./nginx-container/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app:
    environment:
      - TELEPATH_API_LOCATION=http://localhost:80
    container_name: app
    restart: always
    depends_on:
      - api
    build: .

  api:
    environment:
      - DB_HOST=mongodb://mongo/telepath-api
    container_name: api
    restart: always
    image: telepath-api:latest
    depends_on:
      - mongo
    links:
      - mongo
      
  mongo:
    container_name: mongo
    image: mongo